### ISSUE TITLE
[Upstream Issue] Missing build package 'npm-registry-client'

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#440]
It appears `npm-registry-client` is not installed with npm 3.3.10. I installed it in the `build` folder and then it finished the build. I have this issue with Atom v1.2.3 building as well.

```
[~/src/n1-git]  > makepkg -sic
==> Making package: nylas-git 0.3.23.r28.g39a142d-1 (Fri Nov 20 21:50:24 EST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating nylas git repo...
Fetching origin
==> Validating source files with md5sums...
    nylas ... Skipped
==> Extracting sources...
  -> Creating working copy of N1 git repo...
Cloning into 'nylas'...
done.
==> Starting pkgver()...
==> Starting prepare()...
==> Starting build()...
Node: v5.1.0
npm: v3.4.1

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/home/mbilker/src/n1-git/src/nylas/.npmrc" install --loglevel error --cwd=/home/mbilker/src/n1-git/src/nylas/build --ignoreStdout=true 

WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"5.1.0","npm":"3.4.1"})


---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ "/home/mbilker/src/n1-git/src/nylas/build/node_modules/.bin/npm" --userconfig="/home/mbilker/src/n1-git/src/nylas/.npmrc" --target=0.10.40 install --loglevel error --cwd=/home/mbilker/src/n1-git/src/nylas/apm --ignoreStdout=true 

module.js:340
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/mbilker/src/n1-git/src/nylas/build/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by mbilker** [comment]
Please note. I am running the latest node and the latest npm, but that doesn't impact the build as the build script installs its own npm version.

**Comment by mbilker** [comment]
This error appears to only occur on npm v3.4.1. The directory `build/node_modules/npm-registry-client` contains only the dependent packages and not the source files for `npm-registry-client`:
```
 ~/N1/build/node_modules/npm/node_modules/npm-registry-client   master ●  ls -lh
total 4.0K
drwxr-xr-x. 3 mbilker users 4.0K Nov 20 23:02 node_modules
```

**Comment by mbilker** [comment]
Looks like its a big issue npm/npm#10394

**Comment by mbilker** [comment]
Works in npm v3.5.0

**Comment by bengotow** [comment]
Thanks @mbilker—is there anything we need to do on our end to fix this?

**Comment by mbilker** [comment]
I do not feel anything needs to be done on your end unless you want to add `npm-registry-client` to `build/package.json`.

Arch Linux uses npm v3.4.1 in its community repository, which has the issue. I know most other distributions do not use the absolute latest npm version unless users want to.

**Comment by mbilker** [comment]
Ok. npm v3.5.0 is now the latest (stable) version.
