### ISSUE TITLE
script/bootstrap issue

### ISSUE THREAD

**Issue by TimNZ** [nylas/N1#2184]
##### What operating system are you using?
OSX 10.11 (El Capitan)

##### What version of N1 are you using?
0.433

./script/bootstrap does not complete cleanly.
./src/coffee-cache and ./src/less-compile-cache are not generated, subsequently ./script/grunt clean fails on executing partial-clean grunt task

```
I:N1 timshnaider$ ./script/bootstrap 
Node: v5.5.0
npm: v3.3.10

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/Users/timshnaider/Desktop/Development/electron/N1/.npmrc" install --loglevel error --cwd=/Users/timshnaider/Desktop/Development/electron/N1/build --ignoreStdout=true 

Loading "generate-module-cache-task.coffee" tasks...ERROR
>> Error: Cannot find module 'semver'
Loading "prebuild-less-task.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache'
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir 'node_modules'
```

**Comment by bengotow** [comment]
Hmm it looks like the previous step didn't complete successfully. Can you try removing `./build/node_modules` and `./node_modules` from the working directory completely, and then running it again? If that doesn't work, try `cd build; npm install` before running script/bootstrap. I think I've seen this a couple times but I'm not sure what the root cause is.

**Comment by TimNZ** [comment]
There was no <home>./node_modules.
Typically you would do an 'npm install' in home of a package but since I
couldn't actually find any build instructions beyond this page
(https://github.com/nylas/N1/blob/master/CONTRIBUTING.md) I did
'./script/bootstrap' after the clone, which doesn't do npm install in home.
Did a npm install in home first, no more errors from script/bootstrap.
But I had to blow away the entire N1 dir and re-clone as script/bootstrap and
script/build didn't result in an electron directory anymore after I had tried
the '/script grunt clean' was still getting the missing coffee files errors.
You might want to create a Build docs page and test the workflow again.


On Tue, May 10, 2016 at 7:00 PM Ben Gotow <notifications@github.com> wrote:
Hmm it looks like the previous step didn't complete successfully. Can you try
removing ./build/node_modules and ./node_modules from the working directory completely, and then running it again? If that
doesn't work, try cd build; npm install before running script/bootstrap. I think I've seen this a couple times but I'm
not sure what the root cause is.

**Comment by TimNZ** [comment]
Still no ../src/coffee-cache file referenced in the 'clean' grunt task.

**Comment by bengotow** [comment]
Hey! Following the instructions on that page is correct. `script/bootstrap` should do everything, and running `npm install` in the main folder may build the modules with native code for the wrong target (your installed Node version, not Electron).

The CI servers actually run `script/bootstrap` from scratch on every commit, so this /should/ be working! Could you try running `script/bootstrap -v` for verbose mode and see if anything looks relevant?

**Comment by TimNZ** [comment]
Get the errors again without doing 'npm install', snippet below.  Doesn't look like I get additional output with -v

```
I:N1 timshnaider$ ./script/bootstrap -v
Node: v5.5.0
npm: v3.5.3

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/Users/timshnaider/Desktop/Development/electron/N1/.npmrc" install --loglevel error --cwd=/Users/timshnaider/Desktop/Development/electron/N1/build --ignoreStdout=true 

WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"5.5.0","npm":"3.5.3"})
Loading "generate-module-cache-task.coffee" tasks...ERROR
>> Error: Cannot find module 'semver'
Loading "prebuild-less-task.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache'
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir 'node_modules'

Running "add-nylas-build-resources" task
No extra Nylas resources added

Done, without errors.
```

**Comment by bengotow** [comment]
Hmm that's strange. Could you try with Node 4? (You can use `nvm` to keep both versions and switch between them on the command line.) We run CI builds with `0.12`, `4.2` and `5`, but I'm not sure we've tried `5.5` on the Mac. Other than that, I'm really not sure what's going on...

**Comment by TimNZ** [comment]
Tried on a Linux Centos 6.7 server, same result
It also failed further down the bootstrap chain but that's likely a server config issue

It's entirely possible you haven't tested on a clean server for a while or will the CI do that?  
Perhaps CI has dependencies already installed globally?

```
[root@cloudglue2 N1]# ./script/bootstrap 
Node: v0.10.42
npm: v3.8.9

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/opt/N1/.npmrc" install --loglevel error --cwd=/opt/N1/build --ignoreStdout=true 

Loading "babel-task.js" tasks...ERROR
>> Error: Cannot find module 'babel-core'
Loading "generate-module-cache-task.coffee" tasks...ERROR
>> Error: Cannot find module 'semver'
Loading "prebuild-less-task.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache'
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'node_modules'

Running "add-nylas-build-resources" task
No extra Nylas resources added

Done, without errors.


---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ "/opt/N1/build/node_modules/.bin/npm" --userconfig="/opt/N1/.npmrc" --target=0.10.40 install --loglevel error --cwd=/opt/N1/apm --ignoreStdout=true 
```

**Comment by bengotow** [comment]
Hmm - that doesn't look quite the same - it seems to be continuing properly there (on to the Installing APM step.) Is that the end of the output or is the script continuing?

**Comment by TimNZ** [comment]
It continues.  What is the same is the errors in the 'Installing N1 build tools' block.

I don't want to be difficult but I think I've provided plenty of info - it errors on an OSX and Linux instance.

Secondly there is the issue with the missing src/coffee-cache referenced in clean-task.coffee.

Don't know what else I can say or do here.

**Comment by bengotow** [comment]
Hey! Ahh ok - so just ignore those errors, it looks like if you let it run everything completes successfully (see below for what it should look like when everything is fine). 

It looks like those errors are coming from grunt tasks that are part of the build and not necessary for script/bootstrap. I'll see if we can get them resolved since they definitely look like they're important in the output.


```
cip-192-168-1-27:build bengotow$ cd ../../../
ip-192-168-1-27:Edgehill bengotow$ mkdir temp
ip-192-168-1-27:Edgehill bengotow$ cd temp/
ip-192-168-1-27:temp bengotow$ git clone git@github.com:nylas/N1.git
Cloning into 'N1'...
remote: Counting objects: 46248, done.
remote: Compressing objects: 100% (797/797), done.
remote: Total 46248 (delta 406), reused 0 (delta 0), pack-reused 45441
Receiving objects: 100% (46248/46248), 72.78 MiB | 1.55 MiB/s, done.
Resolving deltas: 100% (28651/28651), done.
Checking connectivity... done.
ip-192-168-1-27:temp bengotow$ cd N1/
ip-192-168-1-27:N1 bengotow$ script/bootstrap 
Node: v4.4.4
npm: v2.15.1

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/Edgehill/temp/N1/.npmrc" install --loglevel error --cwd=/Edgehill/temp/N1/build --ignoreStdout=true 

2016-05-10 18:53:37.644 xcodebuild[8884:241696] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-05-10 18:53:57.365 xcodebuild[9185:242314] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Loading "babel-task.js" tasks...ERROR
>> Error: Cannot find module 'babel-core'
Loading "generate-module-cache-task.coffee" tasks...ERROR
>> Error: Cannot find module 'semver'
Loading "prebuild-less-task.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache'
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir 'node_modules'

Running "add-nylas-build-resources" task
No extra Nylas resources added

Done, without errors.


---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ "/Edgehill/temp/N1/build/node_modules/.bin/npm" --userconfig="/Edgehill/temp/N1/.npmrc" --target=0.10.40 install --loglevel error --cwd=/Edgehill/temp/N1/apm --ignoreStdout=true 

2016-05-10 18:54:46.459 xcodebuild[14326:248136] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-05-10 18:54:48.706 xcodebuild[14530:248390] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-05-10 18:55:01.083 xcodebuild[18838:253071] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.


---> Flattening apm package tree
     This runs `npm dedupe` on apm's `npm` dependency.
     We use this to prevent paths over 260 characters on Windows.

     $ "/Edgehill/temp/N1/build/node_modules/.bin/npm" --userconfig="/Edgehill/temp/N1/.npmrc" --target=0.10.40 dedupe --cwd=/Edgehill/temp/N1/apm/node_modules/npm --ignoreStderr=true --ignoreStdout=true 



---> Cleaning apm via `apm clean`

Installing dependencies for composer-emoji
Installing modules ✓
Installing dependencies for composer-templates
Installing modules ✓
Installing dependencies for composer-translate
Installing modules ✓
Installing dependencies for github-contact-card
Installing modules ✓
Installing dependencies for message-view-on-github
Installing modules ✓
Installing dependencies for onboarding
Installing modules ✓
Installing dependencies for participant-profile
Installing modules ✓
Installing dependencies for phishing-detection
Installing modules ✓
Installing dependencies for plugins
Installing modules ✓


---> Installing N1 dependencies & packages via `apm install`

     $ "/Edgehill/temp/N1/apm/node_modules/atom-package-manager/bin/apm" install --loglevel error

Installing modules ✓


---> De-duping packages `apm dedupe`

     $ "/Edgehill/temp/N1/apm/node_modules/atom-package-manager/bin/apm" dedupe --quiet fs-plus humanize-plus roaster season grim

Deduping modules ✓


---> Request version `apm dedupe`

     $ "/Edgehill/temp/N1/apm/node_modules/atom-package-manager/bin/apm" dedupe --quiet request semver --cwd=/Edgehill/temp/N1/apm/node_modules/atom-package-manager --env=[object Object] 

Deduping modules ✓


---> Getting latest Electron

     $ "/Edgehill/temp/N1/build/node_modules/.bin/grunt" download-electron --gruntfile build/Gruntfile.coffee
Running "download-electron" task

Done, without errors.


---> Installing integration test modules

     $ "/Edgehill/temp/N1/build/node_modules/.bin/npm" --userconfig="/Edgehill/temp/N1/.npmrc" install --loglevel error --cwd=/Edgehill/temp/N1/spec_integration --ignoreStdout=true 

Building sqlite3 with command: "/Edgehill/temp/N1/build/node_modules/.bin/npm" install https://github.com/bengotow/node-sqlite3/archive/bengotow/fts5.tar.gz --ignore-scripts && cd node_modules/sqlite3 && "/Edgehill/temp/N1/build/node_modules/npm/node_modules/.bin/node-gyp" configure rebuild --target=0.37.8 --arch=x64 --target_platform=darwin --dist-url=https://atom.io/download/atom-shell --module_name=node_sqlite3 --module_path=../lib/binding/electron-v0.37-darwin-x64
nylas@0.4.34 /Edgehill/temp/N1
├─┬ babel-core@6.8.0
│ ├─┬ babel-generator@6.8.0
│ │ └─┬ detect-indent@3.0.1
│ │   └── minimist@1.2.0 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ └─┬ minimatch@2.0.10
│   └─┬ brace-expansion@1.1.4 
│     ├── balanced-match@0.4.1 
│     └── concat-map@0.0.1 
├─┬ babel-preset-electron@0.37.8
│ ├─┬ babel-plugin-transform-async-to-generator@6.8.0
│ │ └─┬ babel-helper-remap-async-to-generator@6.8.0
│ │   └─┬ babel-traverse@6.8.0
│ │     └─┬ debug@2.2.0 
│ │       └── ms@0.7.1 
│ ├─┬ babel-plugin-transform-class-constructor-call@6.8.0
│ │ └─┬ babel-template@6.8.0
│ │   └─┬ babel-traverse@6.8.0
│ │     └─┬ debug@2.2.0 
│ │       └── ms@0.7.1 
│ ├─┬ babel-plugin-transform-decorators@6.8.0
│ │ ├─┬ babel-helper-define-map@6.8.0
│ │ │ └─┬ babel-helper-function-name@6.8.0
│ │ │   └─┬ babel-traverse@6.8.0
│ │ │     └─┬ debug@2.2.0 
│ │ │       └── ms@0.7.1 
│ │ ├─┬ babel-helper-explode-class@6.8.0
│ │ │ └─┬ babel-traverse@6.8.0
│ │ │   └─┬ debug@2.2.0 
│ │ │     └── ms@0.7.1 
│ │ ├─┬ babel-template@6.8.0
│ │ │ └─┬ babel-traverse@6.8.0
│ │ │   └─┬ debug@2.2.0 
│ │ │     └── ms@0.7.1 
│ │ └─┬ babel-types@6.8.1
│ │   └─┬ babel-traverse@6.8.0
│ │     └─┬ debug@2.2.0 
│ │       └── ms@0.7.1 
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.8.0
│ │ ├─┬ babel-template@6.8.0
│ │ │ └─┬ babel-traverse@6.8.0
│ │ │   └─┬ debug@2.2.0 
│ │ │     └── ms@0.7.1 
│ │ └─┬ babel-types@6.8.1
│ │   └─┬ babel-traverse@6.8.0
│ │     └─┬ debug@2.2.0 
│ │       └── ms@0.7.1 
│ └─┬ babel-plugin-transform-exponentiation-operator@6.8.0
│   └─┬ babel-helper-builder-binary-assignment-operator-visitor@6.8.0
│     ├─┬ babel-helper-explode-assignable-expression@6.8.0
│     │ └─┬ babel-traverse@6.8.0
│     │   └─┬ debug@2.2.0 
│     │     └── ms@0.7.1 
│     └─┬ babel-types@6.8.1
│       └─┬ babel-traverse@6.8.0
│         └─┬ debug@2.2.0 
│           └── ms@0.7.1 
├─┬ babel-preset-react@6.5.0
│ └─┬ babel-plugin-transform-react-jsx@6.8.0
│   └─┬ babel-helper-builder-react-jsx@6.8.0
│     └─┬ babel-types@6.8.1
│       └─┬ babel-traverse@6.8.0
│         └─┬ debug@2.2.0 
│           └── ms@0.7.1 
├─┬ jasmine-tagged@1.1.4
│ └─┬ jasmine-focused@1.0.7
│   └─┬ jasmine-node@1.10.2 (git+https://github.com/kevinsawicki/jasmine-node.git#81af4f953a2b7dfb5bde8331c05362a4b464c5ef)
│     └─┬ gaze@0.3.4
│       └─┬ fileset@0.1.8
│         └─┬ glob@3.2.11
│           └── inherits@2.0.1 
├─┬ juice@1.10.0
│ ├─┬ cheerio@0.19.0
│ │ └─┬ htmlparser2@3.8.3
│ │   └─┬ readable-stream@1.1.14
│ │     ├── core-util-is@1.0.2 
│ │     ├── inherits@2.0.1 
│ │     └── string_decoder@0.10.31 
│ ├── deep-extend@0.4.1 
│ └── util-deprecate@1.0.2 
├─┬ request@2.72.0
│ └─┬ bl@1.1.2
│   └─┬ readable-stream@2.0.6 
│     ├── core-util-is@1.0.2 
│     ├── inherits@2.0.1 
│     ├── isarray@1.0.0 
│     ├── process-nextick-args@1.0.7 
│     ├── string_decoder@0.10.31 
│     └── util-deprecate@1.0.2 
├─┬ rimraf@2.5.2
│ └─┬ glob@7.0.3
│   ├─┬ inflight@1.0.4
│   │ └── wrappy@1.0.1 
│   ├── inherits@2.0.1 
│   ├─┬ minimatch@3.0.0 
│   │ └─┬ brace-expansion@1.1.4 
│   │   ├── balanced-match@0.4.1 
│   │   └── concat-map@0.0.1 
│   └─┬ once@1.3.3 
│     └── wrappy@1.0.1 
├─┬ sanitize-html@1.9.0
│ └─┬ htmlparser2@3.8.3
│   └─┬ readable-stream@1.1.14
│     ├── core-util-is@1.0.2 
│     ├── inherits@2.0.1 
│     └── string_decoder@0.10.31 
├── sqlite3@3.1.2  extraneous
└─┬ underscore.string@3.3.4
  └── util-deprecate@1.0.2 

gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.4.4 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Edgehill/temp/N1/build/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Edgehill/temp/N1/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Edgehill/temp/N1/build/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bengotow/.node-gyp/0.37.8/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bengotow/.node-gyp/0.37.8',
gyp info spawn args   '-Dnode_gyp_dir=/Edgehill/temp/N1/build/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Edgehill/temp/N1/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
2016-05-10 18:58:56.062 xcodebuild[33068:272567] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp info spawn python
gyp info spawn args [ '/Edgehill/temp/N1/build/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Edgehill/temp/N1/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Edgehill/temp/N1/build/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bengotow/.node-gyp/0.37.8/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bengotow/.node-gyp/0.37.8',
gyp info spawn args   '-Dnode_gyp_dir=/Edgehill/temp/N1/build/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Edgehill/temp/N1/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
2016-05-10 18:58:56.783 xcodebuild[33073:272589] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:168560:30: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for(i=0; rc==SQLITE_OK && i<sizeof(aBuiltin)/sizeof(aBuiltin[0]); i++){
                            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:170155:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  if( pPhrase->nTerm>(sizeof(aStatic) / sizeof(aStatic[0])) ){
      ~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:170291:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  if( pNear->nPhrase>(sizeof(aStatic) / sizeof(aStatic[0])) ){
      ~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:171937:30: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for(i=0; rc==SQLITE_OK && i<(sizeof(aFunc) / sizeof(aFunc[0])); i++){
                            ~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:177742:7: warning: unused variable 'cksum3' [-Wunused-variable]
  u64 cksum3 = 0;                 /* Checksum based on contents of indexes */
      ^
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:178716:15: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
    for(j=0; j<sizeof(aConstraint)/sizeof(aConstraint[0]); j++){
             ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:178763:13: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for(i=0; i<sizeof(aConstraint)/sizeof(aConstraint[0]); i++){
           ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:183022:30: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for(i=0; rc==SQLITE_OK && i<sizeof(aBuiltin)/sizeof(aBuiltin[0]); i++){
                            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:9704:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
9 warnings generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:143:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:227:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:505:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:605:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
4 warnings generated.
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc:118:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/statement.cc:322:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Bind);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:370:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Get);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:438:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Run);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:504:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(All);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:601:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Each);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:724:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Reset);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
7 warnings generated.
  SOLINK_MODULE(target) Release/node_sqlite3.node
  COPY ../lib/binding/electron-v0.37-darwin-x64/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp
gyp info ok 
---------------------------------------------
script/bootstrap completed successfully. You can start
N1 via ./N1.sh --dev, or run tests with ./N1.sh --test
ip-192-168-1-27:N1 bengotow$ 
```

**Comment by TimNZ** [comment]
Cool, thanks.  
I should have made clear I can still get it to build and install!

**Comment by bengotow** [comment]
No worries! The errors should be resolved by de4a69b89a5aef6f1875f9f5b31339ed02910c8f. I'm actually a little surprised that missing `require` statements didn't stop `grunt`. I think the problem is that we use the same Gruntfile for both `script/bootstrap`, and `script/build`, and it tries to load all tasks before running. Some of the tasks reference node modules in the parent directory that are actually parts of the app, but haven't been fetched yet when `script/bootstrap` is first run.
